version: '2'
services:
  datasci:
    container_name: data-science-cpu
    build:
      context: ../../../
      dockerfile: Data-Science-Images/Data-Science/CPU/Dockerfile
    ports: 
      - "8888:8888"
    image: joshcole/data-science-cpu:latest